name = "web"
main = "index.js"
account_id = "71b8b36b4e3ecb2a6a7f60a46fcf0d31" # scraper.workers.dev
workers_dev = true
compatibility_date = "2023-06-19"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "dev-recipes-db"
database_id = "99a61b69-e615-4ada-b908-94a2e4b579bd"